In [1]:
import random
import numpy as np

from collections import Counter

In [2]:
P1_START = 0
P2_START = 0
FINISH = 10
ITER = 1000000

P1_MOVES, P2_MOVES = [1, 3, 5], [2, 4, 6]

In [3]:
def play_game(p1_moves=P1_MOVES, p2_moves=P2_MOVES):
    p1_score, p2_score = P1_START, P2_START
    
    while True:
        move = random.randint(1, 6)
        
        if move in p1_moves:
            p1_score += move
        elif move in p2_moves:
            p2_score += move
            
        if p1_score >= FINISH or p2_score >= FINISH:
            break
    return {
        'player_1': p1_score, 
        'player_2': p2_score 
    }

In [4]:
def simulate_game_n_times(n=ITER):
    p1_wins, p2_wins = 0, 0
    
    for _ in range(n):
        game_res = play_game()
        
        if game_res['player_1'] > game_res['player_2']:
            p1_wins += 1
        else:
            p2_wins += 1
    return {
        'p1_wins': p1_wins,
        'p2_wins': p2_wins
    }

In [5]:
%%time
sim_res = simulate_game_n_times()

print("Probability of winnings for P1 and P2 in accordance:")
print(f"{round(sim_res['p1_wins'] / ITER * 100, 3)}%, {round(sim_res['p2_wins'] / ITER * 100, 3)}%")

Probability of winnings for P1 and P2 in accordance:
36.319%, 63.681%
CPU times: total: 5.16 s
Wall time: 5.15 s


In [6]:
p1_probs = sim_res['p1_wins'] / ITER
p2_probs = sim_res['p2_wins'] / ITER

In [7]:
def calculate_ha_odds(p1_prob, p2_prob, margin=0.05):
    return {
        'p1_pure_odd': 1 / p1_prob,
        'p1_margin_odd': (1 - margin) / p1_prob,
        'p2_pure_odd': 1 / p2_prob,
        'p2_margin_odd': (1 - margin) / p2_prob
    }

In [8]:
odds = calculate_ha_odds(p1_probs, p2_probs, margin=0.1)

In [9]:
odds

{'p1_pure_odd': 2.7533797736721826,
 'p1_margin_odd': 2.4780417963049644,
 'p2_pure_odd': 1.5703270991347498,
 'p2_margin_odd': 1.4132943892212748}

In [10]:
def get_scores_probs_c(n=ITER):
    all_res = []
    
    for _ in range(n):
        game_res = play_game()
        all_res.append(tuple(game_res.values()))
    
    res = Counter(all_res)
    return {key: value / n for key, value in res.items()}

In [11]:
probs_c = get_scores_probs_c()
probs_c

{(1, 10): 0.034357,
 (9, 12): 0.014933,
 (13, 8): 0.008534,
 (5, 12): 0.0287,
 (11, 0): 0.025072,
 (14, 6): 0.007979,
 (4, 14): 0.00623,
 (11, 4): 0.017764,
 (10, 6): 0.031596,
 (0, 12): 0.053994,
 (4, 12): 0.014722,
 (5, 10): 0.04229,
 (12, 4): 0.010075,
 (10, 0): 0.040781,
 (13, 6): 0.010634,
 (5, 14): 0.01111,
 (6, 10): 0.033227,
 (3, 10): 0.03747,
 (0, 10): 0.086612,
 (2, 12): 0.007208,
 (10, 8): 0.023721,
 (6, 12): 0.023029,
 (1, 12): 0.022947,
 (11, 6): 0.023836,
 (8, 10): 0.026795,
 (10, 4): 0.023793,
 (11, 2): 0.013157,
 (12, 6): 0.014331,
 (2, 10): 0.010268,
 (14, 0): 0.005692,
 (7, 12): 0.011832,
 (13, 2): 0.005579,
 (4, 10): 0.020932,
 (14, 8): 0.007065,
 (6, 14): 0.009946,
 (10, 2): 0.017965,
 (14, 2): 0.003946,
 (9, 10): 0.02041,
 (12, 2): 0.007155,
 (7, 10): 0.01656,
 (3, 14): 0.009494,
 (1, 14): 0.008553,
 (12, 8): 0.012708,
 (13, 0): 0.010375,
 (8, 12): 0.019092,
 (3, 12): 0.024982,
 (11, 8): 0.018657,
 (8, 14): 0.008282,
 (12, 0): 0.010398,
 (13, 4): 0.007803,
 (0, 14)

In [12]:
def get_scores_probs_np(n=ITER):
    total_res = np.zeros((15, 15))
    for _ in range(n):
        game_res = play_game()
        total_res[game_res['player_1'], game_res['player_2']] += 1
    return total_res / total_res.sum()

In [13]:
probs = get_scores_probs_np()

In [14]:
probs

array([[0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.086659, 0.      ,
        0.053714, 0.      , 0.016188],
       [0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.034903, 0.      ,
        0.023128, 0.      , 0.00853 ],
       [0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.010007, 0.      ,
        0.007106, 0.      , 0.003029],
       [0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.036699, 0.      ,
        0.025104, 0.      , 0.009485],
       [0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.02105 , 0.      ,
        0.014633, 0.      , 0.006251],
       [0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.042794,

In [15]:
def ha_odds(probs, margin=0.05):
    p1_probs = probs[10:, :].sum()
    p2_probs = 1 - p1_probs
    payout_ratio = 1 - margin
    return {
        'p1_odd': payout_ratio / p1_probs,
        'p2_odd': payout_ratio / p2_probs
    }

In [16]:
ha_odds(probs)

{'p1_odd': 2.6099259605214353, 'p2_odd': 1.4936989489076344}

In [17]:
probs

array([[0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.086659, 0.      ,
        0.053714, 0.      , 0.016188],
       [0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.034903, 0.      ,
        0.023128, 0.      , 0.00853 ],
       [0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.010007, 0.      ,
        0.007106, 0.      , 0.003029],
       [0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.036699, 0.      ,
        0.025104, 0.      , 0.009485],
       [0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.02105 , 0.      ,
        0.014633, 0.      , 0.006251],
       [0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
        0.      , 0.      , 0.      , 0.      , 0.042794,

In [18]:
def ou_odds(
    probs: np.array,
    param: float, 
    margin=0.05
) -> dict:
    '''
    Function docs are starting here ...
    '''
    idx = int(param) + 1
    
    payout_ratio = 1 - margin
    return {
        'p1_odd_over': payout_ratio / probs[idx:, :].sum(),
        'p1_odd_under': payout_ratio / probs[:idx, :].sum(),
        'p2_odd_over': payout_ratio / probs[:, idx:].sum(),
        'p2_odd_under': payout_ratio / probs[:, :idx].sum()
    }    

In [19]:
ou_odds.__doc__

'\n    Function docs are starting here ...\n    '

In [20]:
ou_odds(probs=probs, param=4.5)

{'p1_odd_over': 1.4762693585531936,
 'p1_odd_under': 2.6649012864460313,
 'p2_odd_over': 1.1953083518081868,
 'p2_odd_under': 4.629043103700311}

In [21]:
def both_players_to_score_odd(
    probs: np.array, 
    margin=0.05):
    
    payout_ratio = 1 - margin
    
    return {
        'Odd for both players to score:': payout_ratio / (1 - (probs[0, :].sum() + probs[:, 0].sum()))
    }
    

In [22]:
both_players_to_score_odd(probs)

{'Odd for both players to score:': 1.2637465695931933}

In [23]:
def player_n_has_no_score_odd(
    probs: np.array, 
    margin=0.05):
    
    payout_ratio = 1 - margin 

    return {
        'Player 1 has no score odd:': payout_ratio / (probs[0, :].sum()),
        'Player 2 has no score odd:': payout_ratio / (probs[:, 0].sum())
    }
    

In [24]:
player_n_has_no_score_odd(probs)

{'Player 1 has no score odd:': 6.067922407240628,
 'Player 2 has no score odd:': 10.359191328811635}

In [37]:
cols = np.tile(np.array(range(15)), 15).reshape(15, 15)
cols

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6

In [39]:
rows = np.repeat(np.array(range(15)), 15).reshape(15, 15)
rows

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13],
       [14, 14, 14, 14, 14, 14, 14

In [44]:
mask_p2 = cols - rows
mask_p2

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14],
       [ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
         12,  13],
       [ -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
         11,  12],
       [ -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
         10,  11],
       [ -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
          9,  10],
       [ -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,
          8,   9],
       [ -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,
          7,   8],
       [ -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
          6,   7],
       [ -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,
          5,   6],
       [ -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,
          4,   5],
       [-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
       

In [45]:
mask_p1 = - mask_p2
mask_p1

array([[  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12,
        -13, -14],
       [  1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11,
        -12, -13],
       [  2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10,
        -11, -12],
       [  3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9,
        -10, -11],
       [  4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,
         -9, -10],
       [  5,   4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,
         -8,  -9],
       [  6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6,
         -7,  -8],
       [  7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5,
         -6,  -7],
       [  8,   7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,
         -5,  -6],
       [  9,   8,   7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3,
         -4,  -5],
       [ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2,
       

In [52]:
def n_handicap_odd(probs, n: float, margin=0.05):
    
    payout_ratio = 1 - margin
    
    p1_more_n = probs[mask_p1 > n].sum()
    p1_less_n = probs[(mask_p1 < n) & (mask_p1 > 0)].sum()
    
    p2_more_n = probs[mask_p2 > n].sum()
    p2_less_n = probs[(mask_p2 < n) & (mask_p2 > 0)].sum()
    
    print(p1_less_n, p2_less_n, p1_more_n, p2_more_n, p1_less_n + p2_less_n + p1_more_n + p2_more_n)
    
    return {
        'Odd p1 has n more points': payout_ratio / p1_more_n,
        'Odd p1 has n less points': payout_ratio / p1_less_n,
        'Odd p2 has n more points': payout_ratio / p2_more_n,
        'Odd p2 has n less points': payout_ratio / p2_less_n     
    }
    

In [53]:
n_handicap_odd(probs, n = 3.5)

0.042409 0.07831199999999999 0.321586 0.557693 1.0


{'Odd p1 has n more points': 2.954108698761762,
 'Odd p1 has n less points': 22.400905468178923,
 'Odd p2 has n more points': 1.703446161239248,
 'Odd p2 has n less points': 12.13096332618245}